import { StyleSheet } from "react-native";
import { colors, spacing, typography } from "../../../theme";
import { CARD_WIDTH, CARD_HEIGHT, IMAGE_HEIGHT } from "./constants";

export const styles = StyleSheet.create({
	modalOverlay: {
		flex: 1,
		backgroundColor: colors.overlayMedium,
		justifyContent: "center",
		alignItems: "center",
	},
	cardWrapper: {
		width: CARD_WIDTH,
	},
	cardContent: {
		width: CARD_WIDTH,
		height: CARD_HEIGHT,
		backgroundColor: colors.background,
		borderRadius: 12,
		overflow: "hidden",
	},
	imageContainer: {
		height: IMAGE_HEIGHT,
	},
	imageSkeleton: {
		...(StyleSheet.absoluteFill as object),
		backgroundColor: colors.surfaceLight,
	},
	still: {
		width: "100%",
		height: IMAGE_HEIGHT,
	},
	imageGradient: {
		position: "absolute",
		bottom: -1,
		left: 0,
		right: 0,
		height: 100,
	},
	stillPlaceholder: {
		width: "100%",
		height: IMAGE_HEIGHT,
		backgroundColor: colors.surfaceLight,
		justifyContent: "center",
		alignItems: "center",
	},
	stillPlaceholderText: {
		fontSize: 40,
		fontWeight: "700",
		color: colors.textMuted,
		letterSpacing: 2,
	},
	metaSection: {
		paddingHorizontal: spacing.lg,
		marginTop: -65,
	},
	overviewContainer: {
		flexGrow: 1,
		flexShrink: 1,
		marginHorizontal: spacing.lg,
	},
	titlePill: {
		flexDirection: "row",
		alignItems: "center",
		alignSelf: "flex-start",
		borderWidth: 1.5,
		borderColor: colors.text,
		borderRadius: 14,
		paddingHorizontal: spacing.sm,
		paddingVertical: 3,
		marginBottom: spacing.sm,
	},
	titlePillText: {
		fontSize: 11,
		fontWeight: "600",
		color: colors.text,
		flexShrink: 1,
		letterSpacing: 0.5,
	},
	titlePillArrowText: {
		fontSize: 14,
		color: colors.text,
		marginLeft: spacing.xs,
	},
	label: {
		...typography.subtitle,
		fontSize: 16,
		fontWeight: "700",
		color: colors.text,
		letterSpacing: 1,
		paddingHorizontal: spacing.sm,
	},
	episodeTitle: {
		...typography.title,
		color: colors.text,
		marginBottom: spacing.xs,
		fontSize: 18,
		paddingHorizontal: spacing.sm,
	},
	metaRow: {
		flexDirection: "row",
		marginTop: spacing.md,
	},
	meta: {
		...typography.caption,
		color: colors.textSecondary,
	},
	overview: {
		...typography.body,
		color: colors.textSecondary,
		marginTop: spacing.sm,
		lineHeight: 20,
		fontSize: 13,
		textAlign: "justify",
	},
	watchButton: {
		backgroundColor: colors.watchedGreen,
		paddingVertical: spacing.md,
		marginHorizontal: spacing.lg,
		marginBottom: spacing.lg,
		borderRadius: 8,
		alignItems: "center",
	},
	actionButtonText: {
		...typography.subtitle,
		fontSize: 14,
		color: colors.text,
	},
	watchedButtonRow: {
		flexDirection: "row",
		gap: spacing.sm,
		marginHorizontal: spacing.lg,
		marginBottom: spacing.lg,
	},
	unwatchButton: {
		flex: 1,
		paddingVertical: spacing.md,
		borderRadius: 8,
		alignItems: "center",
		backgroundColor: colors.destructiveRed,
	},
	rewatchButton: {
		flex: 1,
		backgroundColor: colors.stopBlue,
		paddingVertical: spacing.md,
		borderRadius: 8,
		alignItems: "center",
	},
	buttonInner: {
		flexDirection: "row",
		alignItems: "center",
		gap: spacing.sm,
	},
	buttonBadge: {
		width: 22,
		height: 22,
		borderRadius: 11,
		backgroundColor: colors.text,
		alignItems: "center",
		justifyContent: "center",
	},
	buttonBadgeText: {
		fontSize: 11,
		fontWeight: "700",
	},
	dotRow: {
		flexDirection: "row",
		justifyContent: "center",
		alignItems: "center",
		gap: 6,
		marginTop: spacing.sm,
	},
	dot: {
		width: 6,
		height: 6,
		borderRadius: 3,
		backgroundColor: colors.textMuted,
		opacity: 0.4,
	},
	dotActive: {
		width: 8,
		height: 8,
		borderRadius: 4,
		opacity: 1,
		backgroundColor: colors.text,
	},
	skeletonBody: {
		padding: spacing.lg,
		gap: spacing.sm,
	},
	skeletonTitle: {
		height: 16,
		width: "60%",
		borderRadius: 4,
		backgroundColor: colors.border,
		marginBottom: spacing.sm,
	},
	skeletonLine: {
		height: 12,
		borderRadius: 4,
		backgroundColor: colors.border,
		marginBottom: spacing.sm,
	},
	skeletonLineShort: {
		height: 12,
		width: "70%",
		borderRadius: 4,
		backgroundColor: colors.border,
	},
	backfillContent: {
		backgroundColor: colors.background,
		borderRadius: 12,
		padding: spacing.lg,
	},
	backfillTitle: {
		...typography.subtitle,
		fontSize: 16,
		textAlign: "center",
		marginBottom: spacing.sm,
	},
	backfillHint: {
		...typography.caption,
		color: colors.textSecondary,
		textAlign: "center",
		marginBottom: spacing.lg,
	},
	backfillButton: {
		paddingVertical: spacing.md,
		borderRadius: 8,
		alignItems: "center",
	},
	backfillButtonText: {
		...typography.subtitle,
		fontSize: 14,
		color: colors.text,
	},
	backfillButtonOutline: {
		paddingVertical: spacing.md,
		borderRadius: 8,
		alignItems: "center",
		borderWidth: 1.5,
		borderColor: colors.text,
		marginTop: spacing.sm,
	},
	backfillButtonOutlineText: {
		...typography.subtitle,
		fontSize: 14,
		color: colors.text,
	},
	backfillCancel: {
		paddingVertical: spacing.sm,
		alignItems: "center",
		marginTop: spacing.sm,
	},
	backfillCancelText: {
		...typography.caption,
		color: colors.textMuted,
	},
});
